/*
 * usbimager/lang.c
 *
 * Copyright (C) 2020 bzt (bztsrc@gitlab)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * @brief Multilanguage support. This file MUST BE encoded in UTF-8!
 *
 */

#include "lang.h"

/**
 * Translations
 */
char *dict[NUMLANGS][NUMTEXTS + 1] = {
    {
        "en",
        "Verify",
        "Write",

        "Error",
        "Write verification failed.",
        "An error occurred while writing to the target device.",
        "An error occurred while reading the source file.",
        "Please select a valid target.",
        "Unable to dismount volume or lock the target device",
        "Unable to umount volumes on target device",
        "Unable to open target volume",
        "An error occurred while opening the target device.",
        "Encrypted ZIP not supported",
        "Unsupported compression method in ZIP",
        "Decompressor error",
        "Please select a readable source file.",
        "Done. Image written successfully.",
        "%d hours and %d minutes left",
        "%d hours and %d minute left",
        "%d hour and %d minutes left",
        "%d hour and %d minute left",
        "%d minutes left",
        "%d minute left",
        "less than a minute left",
        "so far",

        "OK",
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Yesterday",
        "Just now",
        "%d minutes ago",
        "%d hours ago",
        "an hour ago",
        "Open",
        "Cancel",
        "Recently Used",
        "Home",
        "Downloads",
        "Filesystem",
        "Name",
        "Size",
        "Modified",
        "Show all files"
    },
    {
        "es",
        "Verificar",
        "Escribir",
        
        "Error",
        "La verificación de escritura falló.",
        "Se produjo un error al escribir en el dispositivo de destino.",
        "Se produjo un error al leer el archivo fuente.",
        "Por favor, seleccione un objetivo válido.",
        "No se puede desmontar el volumen o bloquear el dispositivo de destino",
        "No se pueden desmontar volúmenes en el dispositivo de destino",
        "No se puede abrir el volumen objetivo",
        "Se produjo un error al abrir el dispositivo de destino.",
        "ZIP cifrado no compatible",
        "Método de compresión no compatible en ZIP",
        "Error descompresor",
        "Seleccione un archivo fuente legible.",
        "Hecho. Imagen escrita con éxito.",
        "Quedan %d horas y %d minutos",
        "Quedan %d horas y %d minuto",
        "Quedan %d hora y %d minutos",
        "Quedan %d hora y %d minuto",
        "Quedan %d minutos",
        "Quedan %d minuto",
        "Queda menos de un minuto",
        "hasta aquí",
        
        "Okay",
        "Domingo",
        "Lunes",
        "Martes",
        "Miércoles",
        "Jueves",
        "Viernes",
        "Sábado",
        "Ayer",
        "Justo ahora",
        "hace %d minutos",
        "hace %d horas",
        "hace una hora",
        "Abierto",
        "Cancelar",
        "Recientemente usado",
        "Hogar",
        "Descargas",
        "Sistema de archivos",
        "Nombre",
        "Talla",
        "Modificado",
        "Mostrar todos los archivos"
    },
    {
        "de",
        "Überprüfen",
        "Ausschreiben",
        
        "Fehler",
        "Schreibüberprüfung fehlgeschlagen.",
        "Beim Schreiben auf das Zielgerät ist ein Fehler aufgetreten.",
        "Beim Lesen der Quelldatei ist ein Fehler aufgetreten.",
        "Bitte wählen Sie ein gültiges Ziel.",
        "Das Volume kann nicht abgemeldet oder das Zielgerät gesperrt werden",
        "Volumes auf dem Zielgerät können nicht bereitgestellt werden",
        "Zielvolume kann nicht geöffnet werden",
        "Beim Öffnen des Zielgeräts ist ein Fehler aufgetreten.",
        "Verschlüsselte ZIP wird nicht unterstützt",
        "Nicht unterstützte Komprimierungsmethode in ZIP",
        "Dekompressorfehler",
        "Bitte wählen Sie eine lesbare Quelldatei.",
        "Erledigt. Bild erfolgreich geschrieben.",
        "%d Stunden und %d Minuten übrig",
        "%d Stunden und %d Minute übrig",
        "%d Stunde und %d Minuten übrig",
        "%d Stunde und %d Minute übrig",
        "%d Minuten übrig",
        "%d Minute übrig",
        "weniger als eine Minute übrig",
        "bisher",
        
        "OK",
        "Sonntag",
        "Montag",
        "Dienstag",
        "Mittwoch",
        "Donnerstag",
        "Freitag",
        "Samstag",
        "Gestern",
        "Gerade jetzt",
        "%d Minuten her",
        "%d Stunden her",
        "vor einer Stunde",
        "Öffnen",
        "Stornieren",
        "Kürzlich verwendet",
        "Zuhause",
        "Heruntergeladen",
        "Dateisystem",
        "Name",
        "Größe",
        "Geändert",
        "Alle Dateien anzeigen"
    },
    {
        "fr",
        "Vérifier",
        "Écrire",
        
        "Erreur",
        "Échec de la vérification de l'écriture.",
        "Une erreur s'est produite lors de l'écriture sur le périphérique cible.",
        "Une erreur s'est produite lors de la lecture du fichier source.",
        "Veuillez sélectionner une cible valide.",
        "Impossible de démonter le volume ou de verrouiller le périphérique cible",
        "Impossible de démonter les volumes sur le périphérique cible",
        "Impossible d'ouvrir le volume cible",
        "Une erreur s'est produite lors de l'ouverture du périphérique cible.",
        "ZIP crypté non pris en charge",
        "Méthode de compression non prise en charge dans ZIP",
        "Erreur du décompresseur",
        "Veuillez sélectionner un fichier source lisible.",
        "Terminé. Image écrite avec succès.",
        "%d heures et %d minutes restantes",
        "%d heures et %d minute restantes",
        "%d heure et %d minutes restantes",
        "%d heure et %d minute",
        "%d minutes restantes",
        "%d minute restante",
        "moins d'une minute",
        "jusque là",
        
        "OK",
        "Dimanche",
        "Lundi",
        "Mardi",
        "Mercredi",
        "Jeudi",
        "Vendredi",
        "Samedi",
        "Hier",
        "Juste maintenant",
        "Il y a %d minutes",
        "Il y a %d heures",
        "Il y a une heure",
        "Ouvert",
        "Annuler",
        "Utilisé récemment",
        "Accueil",
        "Téléchargements",
        "Système de fichiers",
        "Nom",
        "Taille",
        "Modifié",
        "Afficher tous les fichiers"
    },
    {
        "hu",
        "Ellenőrzés",
        "Kiírás",

        "Hiba",
        "Írás ellenőrzési hiba.",
        "Hiba a céleszköz írása közben.",
        "Hiba a forrásfájl olvasása közben.",
        "Kérlek válassz érvényes céleszközt.",
        "Nem sikerült lecsatolni és zárolni a céleszközt",
        "Nem sikerült lecsatolni a célezközt",
        "Nem sikerült megnyitni a célkötetet",
        "Nem sikerült megnyitni a céleszközt",
        "Titkosított ZIP",
        "Ismeretlen tömörítési metódus a ZIPben",
        "Kitömörítő könyvtár hiba",
        "Kérlek válassz egy olvasható forrásfájlt.",
        "Kész. A lemezképet sikeresen kiírtam.",
        "%d óra és %d perc van vissza",
        "%d óra és %d perc van vissza",
        "%d óra és %d perc van vissza",
        "%d óra és %d perc van vissza",
        "még %d perc",
        "még %d perc",
        "már csak egy perc",
        "ezidáig",

        "OK",
        "Vasárnap",
        "Hétfő",
        "Kedd",
        "Szerda",
        "Csütörtök",
        "Péntek",
        "Szombat",
        "tegnap",
        "épp most",
        "%d perce",
        "%d órája",
        "egy órája",
        "Megnyitás",
        "Mégsem",
        "Legutóbb használtak",
        "Saját mappa",
        "Letöltések",
        "Fájlrendszer",
        "Név",
        "Méret",
        "Módosítva",
        "Minden fájl mutatása"
    },
    {
        "it",
        "Verificare",
        "Scrivi",
        
        "Errore",
        "Verifica della scrittura non riuscita.",
        "Si è verificato un errore durante la scrittura sul dispositivo di destinazione.",
        "Si è verificato un errore durante la lettura del file di origine.",
        "Seleziona un obiettivo valido.",
        "Impossibile smontare il volume o bloccare il dispositivo di destinazione",
        "Impossibile smontare i volumi sul dispositivo di destinazione",
        "Impossibile aprire il volume di destinazione",
        "Si è verificato un errore durante l'apertura del dispositivo di destinazione.",
        "ZIP crittografato non supportato",
        "Metodo di compressione non supportato in ZIP",
        "Errore del decompressore",
        "Seleziona un file sorgente leggibile.",
        "Fatto. Immagine scritta con successo.",
        "%d ore e %d minuti rimanenti",
        "%d ore e %d minuto rimanenti",
        "%d ora e %d minuti rimanenti",
        "%d ora e %d minuto rimanenti",
        "%d minuti rimanenti",
        "%d minuto rimanente",
        "meno di un minuto rimasto",
        "finora",
        
        "OK",
        "Domenica",
        "Lunedi",
        "Martedì",
        "Mercoledì",
        "Giovedi",
        "Venerdì",
        "Sabato",
        "Ieri",
        "Proprio adesso",
        "%d minuti fa",
        "%d ore fa",
        "Un'ora fa",
        "Aperto",
        "Annulla",
        "Usato di recente",
        "Casa",
        "Scaricata",
        "Filesistema",
        "Nome",
        "Taglia",
        "Modificata",
        "Mostra tutti i file"
    },
    {
        "nl",
        "Controleren",
        "Schrijf op",
        
        "Fout",
        "Verificatie van schrijven mislukt.",
        "Er is een fout opgetreden tijdens het schrijven naar het doelapparaat.",
        "Er is een fout opgetreden tijdens het lezen van het bronbestand.",
        "Selecteer een geldig doel.",
        "Kan volume niet afkoppelen of het doelapparaat vergrendelen",
        "Kan volumes op doelapparaat niet koppelen",
        "Kan doelvolume niet openen",
        "Er is een fout opgetreden bij het openen van het doelapparaat.",
        "Gecodeerde ZIP wordt niet ondersteund",
        "Niet-ondersteunde compressiemethode in ZIP",
        "Decompressorfout",
        "Selecteer een leesbaar bronbestand.",
        "Klaar. Afbeelding succesvol geschreven.",
        "%d uur en %d minuten resterend",
        "%d uur en %d minuut resterend",
        "%d uur en %d minuten resterend",
        "%d uur en %d minuut resterend",
        "%d minuten resterend",
        "%d minuut resterend",
        "minder dan een minuut over",
        "tot nu toe",
        
        "OK",
        "zondag",
        "maandag",
        "dinsdag",
        "woensdag",
        "donderdag",
        "vrijdag",
        "zaterdag",
        "gisteren",
        "zojuist",
        "%d minuten geleden",
        "%d uur geleden",
        "een uur geleden",
        "Open",
        "Annuleren",
        "Onlangs gebruikt",
        "Thuis",
        "Gedownloade",
        "Bestandssysteem",
        "Naam",
        "Afmeting",
        "Gewijzigde",
        "Toon alle bestanden",
    },
    {
        "pl",
        "Zweryfikować",
        "Pisać",
        
        "Błąd",
        "Weryfikacja zapisu nie powiodła się.",
        "Wystąpił błąd podczas zapisywania na urządzeniu docelowym.",
        "Wystąpił błąd podczas odczytu pliku źródłowego.",
        "Wybierz prawidłowy cel.",
        "Nie można odinstalować woluminu ani zablokować urządzenia docelowego",
        "Nie można umountować woluminów na urządzeniu docelowym",
        "Nie można otworzyć woluminu docelowego",
        "Wystąpił błąd podczas otwierania urządzenia docelowego.",
        "Szyfrowane pliki ZIP nie są obsługiwane",
        "Nieobsługiwana metoda kompresji w ZIP",
        "Błąd dekompresora",
        "Wybierz czytelny plik źródłowy.",
        "Gotowy. Obraz zapisany pomyślnie.",
        "pozostało %d godzin i %d minut",
        "pozostało %d godzin i %d minut",
        "pozostało %d godzina i %d minuta",
        "pozostało %d godziny i %d minuty",
        "pozostało %d minut",
        "pozostało %d minuta",
        "pozostała niecała minuta",
        "jak dotąd",
        
        "Dobrze",
        "Niedziela",
        "Poniedziałek",
        "Wtorek",
        "środa",
        "Czwartek",
        "Piątek",
        "Sobota",
        "Wczoraj",
        "Właśnie",
        "%d minut temu",
        "%d godzin temu",
        "godzinę temu",
        "Otwarty",
        "Anuluj",
        "Ostatnio używane",
        "Dom",
        "Pobrano",
        "System plików",
        "Nazwa",
        "Rozmiar",
        "Zmodyfikowano",
        "Pokaż wszystkie pliki"
    },
    {
        "pt",
        "Verificar",
        "Escrever",
        
        "Erro",
        "A verificação de gravação falhou.",
        "Ocorreu um erro ao gravar no dispositivo de destino.",
        "Ocorreu um erro ao ler o arquivo de origem.",
        "Por favor, selecione um destino válido.",
        "Não foi possível desmontar o volume ou bloquear o dispositivo de destino",
        "Não é possível desmontar volumes no dispositivo de destino",
        "Não foi possível abrir o volume de destino",
        "Ocorreu um erro ao abrir o dispositivo de destino.",
        "ZIP criptografado não suportado",
        "Método de compactação não suportado no ZIP",
        "Erro de descompressor",
        "Por favor, selecione um arquivo fonte legível.",
        "Feito. Imagem gravada com sucesso.",
        "%d horas e %d minutos restantes",
        "%d horas e %d minuto restantes",
        "%d hora e %d minutos restantes",
        "%d hora e %d minuto restante",
        "%d minutos restantes",
        "%d minuto restante",
        "menos de um minuto restante",
        "tão longe",
        
        "Está bem",
        "Domingo",
        "Segunda-feira",
        "Terça",
        "Quarta-feira",
        "Quinta-feira",
        "Sexta-feira",
        "Sábado",
        "Ontem",
        "Agora mesmo",
        "Há %d minutos",
        "Há %d horas",
        "Uma hora atrás",
        "Aberto",
        "Cancelar",
        "Usado recentemente",
        "Casa",
        "Transferido",
        "Sistema de arquivo",
        "Nome",
        "Tamanho",
        "Modificado",
        "Mostrar todos os arquivos"
    },
    {
        "ga",
        "Fíoraigh",
        "Scríobh amach",
        
        "Earráid",
        "Theip ar fhíorú scríofa.",
        "Tharla earráid agus an sprioc-ghléas á scríobh.",
        "Tharla earráid agus an comhad foinse á léamh.",
        "Roghnaigh sprioc bhailí le do thoil.",
        "Ní féidir toirt a dhícheangal nó an sprioc-ghléas a ghlasáil",
        "Ní féidir méideanna a choigilt ar an sprioc-ghléas",
        "Ní féidir an sprioc-sprioc a oscailt",
        "Tharla earráid agus an sprioc-ghléas á oscailt.",
        "Níor tacaíodh le ZIP Criptithe",
        "Modh comhbhrú gan tacaíocht i ZIP",
        "Earráid dhí-chomhbhrúite",
        "Roghnaigh comhad foinse inléite le do thoil.",
        "Íomhá scríofa go rathúil.",
        "%d uair an chloig agus %d nóiméad fágtha",
        "%d uair an chloig agus %d fágtha nóiméad",
        "%d uair an chloig agus %d nóiméad fágtha",
        "%d uair an chloig agus %d fágtha nóiméad",
        "%d nóiméad fágtha",
        "%d nóiméad fágtha",
        "níos lú ná nóiméad fágtha",
        "go dtí seo",
        
        "OK",
        "Dé Domhnaigh",
        "Dé Luain",
        "Dé Máirt",
        "Dé Céadaoin",
        "Déardaoin",
        "Dé hAoine",
        "Dé Sathairn",
        "Inné",
        "Díreach anois",
        "%d nóiméad ó shin",
        "%d uair an chloig ó shin",
        "uair an chloig ó shin",
        "Oscailte",
        "Cealaigh",
        "A Úsáideadh Le Déanaí",
        "Baile",
        "Íoslódáilte",
        "Córas Comhaid",
        "Ainm",
        "Méid",
        "Athraithe",
        "Taispeáin gach comhad"
    },
    {
        "tr",
        "Doğrulamak",
        "Yaz",
        
        "Hata",
        "Yazma doğrulanamadı.",
        "Hedef cihaza yazılırken bir hata oluştu.",
        "Kaynak dosya okunurken bir hata oluştu.",
        "Lütfen geçerli bir hedef seçin.",
        "Ses düzeyi çıkarılamıyor veya hedef cihaz kilitlenemiyor",
        "Hedef cihazdaki birimler sayılamıyor",
        "Hedef birim açılamıyor",
        "Hedef cihaz açılırken bir hata oluştu.",
        "Şifreli ZIP desteklenmiyor",
        "ZIP'te desteklenmeyen sıkıştırma yöntemi",
        "Sıkıştırıcı hatası",
        "Lütfen okunabilir bir kaynak dosya seçin.",
        "Görüntü başarıyla yazıldı.",
        "%d saat ve %d dakika kaldı",
        "%d saat ve %d dakika kaldı",
        "%d saat ve %d minutea kaldı",
        "%d saat ve %d dakika kaldı",
        "%d dakika kaldı",
        "%d dakika kaldı",
        "bir dakikadan az kaldı",
        "şimdiye kadar",
        
        "Tamam",
        "Pazar",
        "Pazartesi",
        "Salı",
        "Çarşamba",
        "Perşembe",
        "Cuma",
        "Cumartesi",
        "dün",
        "Hemen şimdi",
        "%d dakika önce",
        "%d saat önce",
        "bir saat önce",
        "Açık",
        "Iptal",
        "Son Kullanılanlar",
        "Ev",
        "Indirilen",
        "Dosya sistemi",
        "Ad",
        "Boyut",
        "Modifiye",
        "Tüm dosyaları göster"
    },
    {
        "el",
        "Επαληθεύω",
        "Γράφω",
        
        "Λάθος",
        "Η εγγραφή απέτυχε.",
        "Παρουσιάστηκε σφάλμα κατά την εγγραφή στη συσκευή προορισμού.",
        "Παρουσιάστηκε σφάλμα κατά την ανάγνωση του αρχείου προέλευσης.",
        "Επιλέξτε έναν έγκυρο στόχο.",
        "Δεν είναι δυνατή η κατάργηση της έντασης ή η δέσμευση της συσκευής προορισμού",
        "Δεν είναι δυνατή η προσαρμογή των τόμων στη συσκευή προορισμού",
        "Δεν είναι δυνατό να ανοίξει η ένταση στόχου",
        "Παρουσιάστηκε σφάλμα κατά το άνοιγμα της συσκευής προορισμού.",
        "Το κρυπτογραφημένο ZIP δεν υποστηρίζεται",
        "Μη υποστηριζόμενη μέθοδος συμπίεσης σε ZIP",
        "Σφάλμα αποσυμπιεστή",
        "Επιλέξτε ένα ευανάγνωστο αρχείο προέλευσης.",
        "Ολοκληρώθηκε. Η εικόνα γράφτηκε με επιτυχία.",
        "%d ώρες και %d λεπτά αριστερά",
        "%d ώρες και %d λεπτά αριστερά",
        "%d ώρα και %d λεπτά αριστερά",
        "%d ώρα και %d λεπτά αριστερά",
        "Απομένουν %d λεπτά",
        "%d λεπτά αριστερά",
        "λιγότερο από ένα λεπτό",
        "μέχρι τώρα",
        
        "Εντάξει",
        "Κυριακή",
        "Δευτέρα",
        "Τρίτη",
        "Αύγουστος",
        "Πέμπτη",
        "Παρασκευή",
        "Σάββατο",
        "Εχθές",
        "Μόλις τώρα",
        "%d λεπτά πριν",
        "πριν από %d ώρες",
        "πριν από μία ώρα",
        "Ανοιξε",
        "Ματαίωση",
        "Πρόσφατα χρησιμοποιημένο",
        "Σπίτι",
        "Λήψεις",
        "Σύστημα αρχείων",
        "Ονομα",
        "Μέγεθος",
        "Τροποποιήθηκε",
        "Εμφάνιση όλων των αρχείων"
    },
    {
        "ru",
        "Проверить",
        "Написать",
        
        "Ошибка",
        "Проверка записи не удалась.",
        "Произошла ошибка при записи на целевое устройство.",
        "Произошла ошибка при чтении исходного файла.",
        "Пожалуйста, выберите действительную цель.",
        "Невозможно отключить том или заблокировать целевое устройство",
        "Невозможно размонтировать тома на целевом устройстве",
        "Невозможно открыть целевой объем",
        "Произошла ошибка при открытии целевого устройства.",
        "Зашифрованный ZIP не поддерживается",
        "Неподдерживаемый метод сжатия в ZIP",
        "Ошибка декомпрессора",
        "Пожалуйста, выберите читаемый исходный файл.",
        "Выполнено. Изображение написано успешно.",
        "%d часов и %d минуты осталось",
        "%d часов и %d минут осталось",
        "%d часа и %d минуты осталось",
        "%d часа и %d минут осталось",
        "осталось %d минут",
        "%d минуты осталось",
        "осталось меньше минуты",
        "слишком далеко",
        
        "OK",
        "Воскресенье",
        "Понедельник",
        "Вторник",
        "среда",
        "Четверг",
        "Пятница",
        "суббота",
        "Вчера",
        "Прямо сейчас",
        "%d минут назад",
        "%d часов назад",
        "час назад",
        "Открыто",
        "Отмена",
        "Недавно использованный",
        "Дом",
        "Загрузки",
        "Файловая система",
        "имя",
        "Размер",
        "модифицированный",
        "Показать все файлы"
    },
    {
        "jp",
        "確認",
        "書く",
        
        "エラー",
        "書き込み検証に失敗しました。",
        "ターゲットデバイスへの書き込み中にエラーが発生しました。",
        "ソースファイルの読み取り中にエラーが発生しました。",
        "有効なターゲットを選択してください。",
        "ボリュームをマウント解除できない、またはターゲットデバイスをロックできない",
        "ターゲットデバイスのボリュームをアンマウントできません",
        "ターゲットボリュームを開けません",
        "ターゲットデバイスを開くときにエラーが発生しました。",
        "暗号化されたZIPはサポートされていません",
        "ZIPでサポートされていない圧縮方法",
        "解凍エラー",
        "読み取り可能なソースファイルを選択してください。",
        "できた 画像が正常に書き込まれました。",
        "残り%d時間と%d分",
        "残り%d時間と%d分",
        "残り%d時間と%d分",
        "残り%d時間と%d分",
        "残り%d分",
        "残り%d分",
        "残り1分未満",
        "これまでのところ",
        
        "はい",
        "日曜日",
        "月曜",
        "火曜日",
        "水曜日",
        "木曜日",
        "金曜日",
        "土曜日",
        "昨日",
        "ちょうど今",
        "%d分前",
        "%d時間前",
        "1時間前",
        "開いた",
        "キャンセル",
        "最近使用された",
        "ホーム",
        "ダウンロード",
        "ファイルシステム",
        "名前",
        "サイズ",
        "修正済み",
        "すべてのファイルを表示"
    },
    {
        "ch",
        "校验",
        "写",
        
        "错误",
        "写验证失败。",
        "写入目标设备时发生错误。",
        "读取源文件时发生错误。",
        "请选择一个有效的目标。",
        "无法卸除音量或锁定目标设备",
        "无法在目标设备上卸载卷",
        "无法打开目标音量",
        "打开目标设备时发生错误。",
        "不支持加密的ZIP",
        "ZIP中不支持的压缩方法",
        "解压缩器错误",
        "请选择可读的源文件。",
        "做完了 图片写入成功。",
        "还剩%d小时和%d分钟",
        "还剩%d小时和%d分钟",
        "还剩%d小时和%d分钟",
        "还剩%d小时和%d分钟",
        "还剩%d分钟",
        "还剩%d分钟",
        "还剩不到一分钟",
        "至今",
        
        "好的",
        "星期日",
        "星期一",
        "星期二",
        "星期三",
        "星期四",
        "星期五",
        "星期六",
        "昨天",
        "现在",
        "%d分钟前",
        "%d小时前",
        "一小时前",
        "打开",
        "取消",
        "最近使用",
        "家",
        "资料下载",
        "系统",
        "名称",
        "尺寸",
        "改性",
        "显示所有文件"
    },
    {
        "ko",
        "확인",
        "쓰다",
        
        "오차",
        "쓰기 확인에 실패했습니다.",
        "대상 장치에 쓰는 동안 오류가 발생했습니다.",
        "소스 파일을 읽는 중 오류가 발생했습니다.",
        "유효한 대상을 선택하십시오.",
        "볼륨을 분리하거나 대상 장치를 잠글 수 없습니다",
        "대상 장치에서 볼륨을 마운트 해제 할 수 없습니다",
        "대상 볼륨을 열 수 없습니다",
        "대상 장치를 여는 중 오류가 발생했습니다.",
        "암호화 된 ZIP은 지원되지 않습니다",
        "ZIP에서 지원되지 않는 압축 방법",
        "압축 해 제기 오류",
        "읽을 수있는 소스 파일을 선택하십시오.",
        "이미지가 성공적으로 작성되었습니다.",
        "%d 시간 및 %d 분 남음",
        "%d 시간 및 %d 분 남음",
        "%d 시간 및 %d 분 남음",
        "%d 시간 및 %d 분 남음",
        "%d 분 남음",
        "%d 분 남음",
        "1 분 미만 남음",
        "지금까지",
        
        "OK",
        "일요일",
        "월요일",
        "화요일",
        "수요일",
        "목요일",
        "금요일",
        "토요일",
        "어제",
        "바로 지금",
        "%d 분 전",
        "%d 시간 전",
        "한 시간 전에",
        "오픈",
        "취소",
        "최근에 사용한",
        "홈",
        "다운로드",
        "파일 시스템",
        "이름",
        "사이즈",
        "수정",
        "모든 파일 표시"
    }
};
